### ISSUE TITLE
Reply to the same thread, if there is already a failure from the same DAG with same execution date

### ISSUE THREAD

**Issue by ggktech2323** [mendhak/Airflow-MS-Teams-Operator#5]
I have 100 table loads, running every 10min, if the source system goes down, I get 100 alerts, and I miss other alerts from different DAG which might come between these alerts.
Is it possible to configure that the 2nd alert from the dag for an execution date is sent as a reply to the 1st alert?

**Comment by mendhak** [comment]
Since this uses the Incoming Webhook for Teams, that's not possible, because it's just a one way communication.  To put it another way, one webhook message = one Teams message.  The only way to do what you're describing is to build your own bot that will receive your messages, create Teams messages and track it and append additional incoming messages to it as a reply.  

If your aim is to reduce noise you'll need to find another way.  For example instead of getting the DAG to alert for each table, maybe an aggregation step that checks all the previous tabls and just issues one pass/fail alert.  Or maybe an external service that has Teams integration.  For some complex DAGs, we use push tests on StatusCake, which in turn notifies Teams if the DAG didn't check in within a certain period.
